---
all:
  children:
    microk8s:
      children:
        microk8s_primary:
          hosts:
            microk8s-node-01:
              ansible_host: 192.168.86.30
              # Subnet router for Tailscale - advertises home network
              tailscale_advertise_routes:
                - "192.168.86.0/24"
        microk8s_workers:
          hosts:
            microk8s-node-03:
              ansible_host: 192.168.86.57
            microk8s-node-04:
              ansible_host: 192.168.86.74
      vars:
        ansible_user: cjchand
        ansible_python_interpreter: /usr/bin/python3
