apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - source-helmrepo-coder.yaml
  - coder-postgres-sealedsecret.yaml
  - coder-postgres-cluster.yaml
  - helmrelease.yaml
