apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - homeassistant/
  - homebridge/
  - homepage/
  - loki-stack/
  - metallb/
  - piped/
  - syncify/
  - coder/
  - tandoor/
  - teslamate/
  - traefik/
  - unifi-controller/
  - uptime-kuma/