apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - source-helmrepo-piped.yaml
  - piped-postgres-sealedsecret.yaml
  # - piped-postgres-cluster.yaml
  - helmrelease.yaml

